### ISSUE TITLE
It seems like only your pillar-1.scss has some setting at the end for smaller screens

### ISSUE THREAD

**Issue by liufuyang** [xriley/pillar-theme#1]
Perhaps you can add this to all your scss files? 😄 

```
// Small devices (landscape phones, less than 768px)
@media (max-width: 767.98px) {
    .resume-wrapper {
	    padding-top: 0;
    }
	
	.resume-header {
		height: auto;
	}
	.resume-header .picture {
		width: 120px;
		@include border-radius(4px);
	}
}
```

**Comment by mardroid** [comment]
in the assets/css Folder, it's also missing at pillar-2.css - pillar-6.css.
I just found it because the mobile view was broken.

@media (max-width: 767.98px) {
  .resume-wrapper {
    padding-top: 0;
  }
  .resume-header {
    height: auto;
  }
  .resume-header .picture {
    width: 120px;
    border-radius: 4px;
  }
}

**Comment by xriley** [comment]
Thanks @liufuyang and @mardroid! 👍😊🤝
I just pushed the fixes to master.
